### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by zjbthomas** [FoelliX/AQL-System#4]
Hi,

When I ran AQL-System follow the guide (https://github.com/FoelliX/AQL-System/wiki/Runthrough), I got the following error message:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at de.foellix.aql.ui.cli.CommandLineInterface.main(CommandLineInterface.java:156)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 13 more
```

May I know what may be the possible reason? Thank you!

**Comment by FoelliX** [comment]
Hi,

the JVM cannot find the JavaFX classes, which are required by the AQL-System's GUI.
To avoid this error, please use Java 8 and make sure the JRE/JDK you are using contains the JavaFX classes.
I suggest to use the JDK downloadable here: https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html 

Cheers,
FoelliX
